[build]
builder = "NIXPACKS"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "export DJANGO_SUPERUSER_USERNAME=admin && export DJANGO_SUPERUSER_EMAIL=admin@example.com && export DJANGO_SUPERUSER_PASSWORD=yourpassword@#! && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py createsuperuser --noinput || true && python manage.py runserver"